dist: bionic
os:
  - linux

sudo: false
addons:
  apt:
    sources:
      - deadsnakes # source required so it finds the package definition below
    packages:
      - python3.8
      - virtualenv
      - python3-pip
      - python3-virtualenv
      - libxslt1-dev
      - python3-lxml

install:
  - "/usr/bin/virtualenv -p /usr/bin/python3.8 /tmp/xml2rfc"
  - "/usr/bin/python3.8 --version"
  - "/tmp/xml2rfc/bin/pip install pyang"
  - "/tmp/xml2rfc/bin/pip install six"
  - "/tmp/xml2rfc/bin/pip install xml2rfc"

script:
  - "PATH=/tmp/xml2rfc/bin:$PATH make"
