#!/bin/bash

set -e

openssl verify -CAfile vendor.crt idevid_00-D0-E5-F2-00-02.crt
openssl cms -verify -in <(base64 -d voucher_00-D0-E5-F2-00-02.b64) -inform DER -CAfile vendor.crt -noout >/dev/null
openssl cms -verify -in <(base64 -d vr_00-D0-E5-F2-00-02.b64) -inform DER -CAfile vendor.crt -noout
openssl cms -verify -in <(base64 -d parboiled_vr_00-D0-E5-F2-00-02.b64) -inform DER -CAfile ownerca_secp384r1.crt -purpose any -noout
