#!/bin/bash

set -e

openssl verify -CAfile vendor.cert idevid_00-D0-E5-F2-00-02.cert
openssl cms -verify -in <(base64 -d voucher_00-D0-E5-F2-00-02.b64) \
        -inform DER -CAfile vendor.cert \
        -certfile masa.cert \
        -noout >/dev/null
openssl cms -verify -in <(base64 -d vr_00-D0-E5-F2-00-02.b64) -inform DER -CAfile vendor.cert -noout
openssl cms -verify -in <(base64 -d parboiled_vr_00-D0-E5-F2-00-02.b64) -inform DER -CAfile ownerca_secp384r1.cert -purpose any -noout
